/**
 * "Slides" export — turn the rendered result into a presentation.
 *
 * Slides is no longer a compose style; it's an export format. We segment the
 * rendered dashboard/notebook into per-section images and assemble a
 * Reveal.js deck (the lib + theme load from CDN; the slide images are inlined
 * as data URLs, so the content travels with the file). PPTX export remains
 * available separately.
 */

import { toPng } from "html-to-image";

function esc(s: string): string {
  return s
    .replace(/&/g, "&amp;")
    .replace(/</g, "&lt;")
    .replace(/>/g, "&gt;")
    .replace(/"/g, "&quot;");
}

/** Find the content root and return its top-level sections as slide units. */
function slideUnits(rootEl: HTMLElement): HTMLElement[] {
  const marked = rootEl.querySelector<HTMLElement>("[data-slides-root]");
  let container: HTMLElement = marked ?? rootEl;
  // Unwrap single-child wrappers (providers, error boundary, the layout
  // column) until we reach the element whose children are the real sections.
  while (container.children.length === 1 && container.firstElementChild instanceof HTMLElement) {
    container = container.firstElementChild;
  }
  const kids = [...container.children].filter((c): c is HTMLElement => c instanceof HTMLElement);
  return kids.length >= 2 ? kids : [marked ?? rootEl];
}

function unitTitle(el: HTMLElement): string | undefined {
  const h = el.querySelector("h1,h2,h3,h4");
  const t = h?.textContent?.trim();
  return t || undefined;
}

/** Capture each section of the rendered result as a slide image. */
export async function captureSlides(
  rootEl: HTMLElement
): Promise<{ title?: string; img: string }[]> {
  const units = slideUnits(rootEl);
  const slides: { title?: string; img: string }[] = [];
  for (const unit of units) {
    if (unit.offsetWidth === 0 || unit.offsetHeight === 0) continue;
    try {
      const img = await toPng(unit, { backgroundColor: "#ffffff", pixelRatio: 2 });
      slides.push({ title: unitTitle(unit), img });
    } catch {
      // Skip a section that can't be snapshotted; the rest still export.
    }
  }
  return slides;
}

/** Assemble a Reveal.js HTML deck. Lib/theme via CDN; images inlined. */
export function buildRevealDeck(title: string, slides: { title?: string; img: string }[]): string {
  const REVEAL = "https://cdn.jsdelivr.net/npm/reveal.js@5.1.0";
  const titleSlide = `<section data-background-color="#0b1220">
      <h1 style="color:#fff;font-size:1.8em">${esc(title)}</h1>
      <p style="color:#9fb0c8">Generated by Hermetic</p>
    </section>`;
  const body = slides
    .map(
      (s) =>
        `<section>${s.title ? `<h2>${esc(s.title)}</h2>` : ""}<img src="${s.img}" alt="${esc(
          s.title ?? "slide"
        )}" /></section>`
    )
    .join("\n      ");

  return `<!doctype html>
<html lang="en">
<head>
<meta charset="utf-8" />
<meta name="viewport" content="width=device-width, initial-scale=1" />
<title>${esc(title)}</title>
<link rel="stylesheet" href="${REVEAL}/dist/reveal.css" />
<link rel="stylesheet" href="${REVEAL}/dist/theme/white.css" id="theme" />
<style>
  .reveal section img { max-height: 78vh; width: auto; margin: 0 auto; border: 1px solid #e4e7eb; border-radius: 8px; box-shadow: 0 2px 10px rgba(0,0,0,.08); }
  .reveal h2 { font-size: 1.3em; margin-bottom: .4em; text-transform: none; }
  .reveal h1 { text-transform: none; }
</style>
</head>
<body>
<div class="reveal"><div class="slides">
      ${titleSlide}
      ${body}
</div></div>
<script src="${REVEAL}/dist/reveal.js"></script>
<script>Reveal.initialize({ hash: true, controls: true, progress: true, center: true });</script>
</body>
</html>`;
}

/** Capture + assemble + download a Reveal deck from a rendered result root. */
export async function downloadAsSlides(rootEl: HTMLElement, title: string): Promise<void> {
  const slides = await captureSlides(rootEl);
  const html = buildRevealDeck(title || "Slides", slides);
  const blob = new Blob([html], { type: "text/html;charset=utf-8" });
  const url = URL.createObjectURL(blob);
  const a = document.createElement("a");
  a.href = url;
  a.download = `${
    (title || "slides")
      .replace(/[^a-z0-9]+/gi, "-")
      .replace(/^-+|-+$/g, "")
      .toLowerCase() || "slides"
  }.html`;
  a.click();
  URL.revokeObjectURL(url);
}
