/**
 * String-level pins on the shipped worker source (the exact code the
 * /api/wasm-worker route serves and the e2e boots). Each pin is a capability
 * the Docker↔wasm parity audit found unpinned: fresh workdir per run, the
 * staged-file DuckDB bridge (D9), the pre-flight lint, the progress bridge,
 * and micropip's deliberate absence.
 */
import { describe, it, expect } from "vitest";
import { WASM_WORKER_SOURCE } from "@/lib/sandbox/wasm/worker-source";
import { preflightLintError } from "@/lib/sandbox/preflight-lint";

const src = WASM_WORKER_SOURCE;

describe("WASM_WORKER_SOURCE — parity pins", () => {
  it("recreates a fresh /data workdir every run (warm-pool cleanup invariant, F7)", () => {
    expect(src).toContain("shutil.rmtree(");
    expect(src).toContain("os.makedirs(");
  });

  it("never loads micropip — runtime package installs stay impossible by design (B5)", () => {
    expect(src).not.toMatch(/micropip/);
  });

  it("registers staged DATA files with DuckDB by their /data path (D9 bridge)", () => {
    // data-shaped extensions only; hermetic_runtime .py files stay unregistered
    expect(src).toContain("__hermeticDuckRegister");
    expect(src).toContain("\\.(csv|tsv|parquet|json|jsonl)$");
    // all three staging channels feed the bridge: files, inline CSV, fetchInputs
    expect(src.match(/duckRegister\(/g)!.length).toBeGreaterThanOrEqual(3);
  });

  it("runs the shared pre-flight lint before executing, failing with the Docker-identical message", () => {
    expect(src).toContain('/script.py"');
    expect(src).toContain("UNDEFINED:");
    expect(src).toContain("SYNTAX:");
    // The templates are GENERATED by the same formatter Docker uses — assert the
    // distinctive wording rode into the worker string (drift-proof by import).
    const undefMsg = preflightLintError({ undefinedNames: [{ name: "x", line: 1 }] })!;
    expect(src).toContain("Do NOT change your analysis approach");
    expect(undefMsg).toContain("Do NOT change your analysis approach");
  });

  it("bridges Python progress() frames to the page as kind:'progress' messages", () => {
    expect(src).toContain("__hermeticProgress");
    expect(src).toContain('kind: "progress"');
    // Result envelopes carry no kind field — a progress frame can never be
    // mistaken for the result (the page resolves only on kind-less messages).
    expect(src).not.toContain('kind: "result"');
  });

  it("the on-demand package regexes shipped INTACT (template-literal escapes, the latent scipy bug)", () => {
    // A single-escaped \\b in the template became a BACKSPACE in the shipped
    // string — the scipy conditional never matched. Assert the real pattern.
    expect(src).toContain("(?:import|from)\\s+scipy\\b");
    expect(src).not.toContain("\bscipy"); // no literal backspace remnants
  });
});
