import { WASM_PRELUDE, WASM_WORK_DIR } from "./runtime-constants";
import { DUCKDB_BOOT_FN_SOURCE, DUCKDB_PY_SHIM } from "./duckdb-worker";
import { UNDEFINED_NAME_CHECKER, preflightLintError } from "../preflight-lint";

/**
 * The pre-flight checker, wrapped for Pyodide: capture its printed markers
 * (it writes to stdout and exits via SystemExit) and hand them back as the
 * expression value. JSON string encoding is valid Python string syntax, so the
 * shared checker embeds verbatim — one checker for both tiers.
 */
const LINT_WRAPPER = `
import io as _io, contextlib as _ctx
_buf = _io.StringIO()
try:
    with _ctx.redirect_stdout(_buf):
        exec(compile(${JSON.stringify(UNDEFINED_NAME_CHECKER)}, "<lint>", "exec"), {})
except SystemExit:
    pass
_buf.getvalue()
`;

/**
 * Retry-facing message templates, generated by the SAME formatter the Docker
 * path uses (preflightLintError) so the wording can never drift between tiers.
 * The worker substitutes the dynamic part into the placeholder at runtime.
 */
const LINT_SYNTAX_TEMPLATE = preflightLintError({
  undefinedNames: [],
  syntaxError: { message: "__HERMETIC_LINT_DETAIL__", line: 0 },
})!;
const LINT_UNDEF_TEMPLATE = preflightLintError({
  undefinedNames: [{ name: "__HERMETIC_LINT_DETAIL__", line: 0 }],
})!.replace("`__HERMETIC_LINT_DETAIL__`", "__HERMETIC_LINT_DETAIL__");

/**
 * The execution Web Worker source (spec §4a / build log D6, D8=self), shared by the
 * `/api/wasm-worker` route (which serves it under WASM_EXEC_CSP) and the E2.5
 * acceptance e2e (which boots THIS exact string) — so the running-app gate can
 * never validate a worker that differs from production.
 *
 * A classic worker (so `importScripts` works) that embeds the SHARED prelude +
 * workdir, so it can never drift from the Node parity executor. Under the Tauri
 * `'self'` CSP it loads Pyodide + packages from the bundled same-origin dist and
 * performs no cross-origin I/O. It returns a RAW envelope {id, exitCode, output,
 * stderr} — the sidecar relay + parseSandboxOutput decode it.
 *
 * Frozen postMessage contract with app/lib/wasm-worker-client:
 *   ← { indexURL, request: WasmExecuteRequest }
 *   → { id, exitCode, output: <output.json|null>, stderr?: <stderr.txt> }
 */
export const WASM_WORKER_SOURCE = `
"use strict";
${DUCKDB_BOOT_FN_SOURCE}
self.onmessage = async (e) => {
  const { indexURL, request } = e.data || {};
  const id = request && request.id;
  // Live progress bridge: the Python prelude's progress() calls this with a
  // small JSON frame; it crosses to the page as a kind:"progress" message
  // (never mistakable for the result envelope, which has no kind field) and
  // the page forwards it to the sidecar. Bounded here AND re-validated by the
  // sidecar relay — the worker is untrusted either way.
  self.__hermeticProgress = (json) => {
    try {
      const p = JSON.parse(String(json));
      self.postMessage({
        kind: "progress",
        id,
        phase: String(p.phase || "analyzing").slice(0, 120),
        ...(p.detail !== undefined ? { detail: String(p.detail).slice(0, 500) } : {}),
        ...(typeof p.fraction === "number" && isFinite(p.fraction) ? { fraction: p.fraction } : {}),
      });
    } catch (_e) { /* advisory channel — drop */ }
  };
  try {
    importScripts(indexURL + "pyodide.js"); // same-origin bundled dist (script-src 'self')
    const pyodide = await self.loadPyodide({ indexURL });
    await pyodide.loadPackage(["numpy", "pandas"]);
    // Heavy packages the Docker image ships are IN the Pyodide distribution but
    // not loaded by default (tens of MB a pandas-only run must not pay for).
    // Load each exactly when the CODE imports it (build log D39; same opt-in
    // shape as codeNeedsDuckDb). Import name → distribution package name.
    // NOTE the double escapes: this file is a TEMPLATE LITERAL, where a bare
    // \\b is a BACKSPACE character — the original single-escaped scipy regex
    // shipped as a broken pattern that never matched (latent: scipy on-demand
    // load silently never fired in the browser worker; caught by the parity
    // audit's string pins).
    const onDemand = [
      [/\\b(?:import|from)\\s+scipy\\b/, "scipy"],
      [/\\b(?:import|from)\\s+matplotlib\\b/, "matplotlib"],
      [/\\b(?:import|from)\\s+sklearn\\b/, "scikit-learn"],
    ];
    const codeText = String(request.code || "");
    const wanted = onDemand.filter(([re]) => re.test(codeText)).map(([, pkg]) => pkg);
    if (wanted.length) await pyodide.loadPackage(wanted);
    // DuckDB is booted only when the request asks (build log D18): the engine is a
    // 41MB wasm module, so a pandas-only run must not pay for it. Parameters arrive
    // as DATA — the CSP allows wasm-unsafe-eval but NOT unsafe-eval.
    if (request.duckdb) {
      await __hermeticBootDuckDb(request.duckdb.base, request.duckdb.aliases || [], !!request.duckdb.spatial);
    }

    const WORK_DIR = ${JSON.stringify(WASM_WORK_DIR)};
    // Staged-file bridge (D9 parity): every DATA-shaped file written to Pyodide's
    // MEMFS is also registered with DuckDB by its exact /data path, so generated
    // SQL like "FROM '/data/step_2.csv'" works as it does in Docker. Later writes
    // to the same path re-register (fetchInputs override the inline CSV).
    const duckRegister = (path, bytes) => {
      if (!request.duckdb || !self.__hermeticDuckRegister) return;
      if (!/\\.(csv|tsv|parquet|json|jsonl)$/i.test(path)) return;
      try { self.__hermeticDuckRegister(path, bytes); } catch (_e) { /* query surfaces it */ }
    };
    const textBytes = (s) => new TextEncoder().encode(String(s));
    // Clean + recreate the workdir, then stage the run's files (the request's files
    // already include the hermetic_runtime package — the sidecar prepends it before
    // dispatch), the input CSV, and optional GeoJSON.
    pyodide.runPython(
      'import shutil, os; shutil.rmtree(' + JSON.stringify(WORK_DIR) +
      ', ignore_errors=True); os.makedirs(' + JSON.stringify(WORK_DIR) + ', exist_ok=True)'
    );
    for (const f of (request.files || [])) {
      const slash = f.path.lastIndexOf("/");
      if (slash > 0) pyodide.FS.mkdirTree(f.path.slice(0, slash));
      pyodide.FS.writeFile(f.path, f.content);
      duckRegister(f.path, textBytes(f.content));
    }
    // Inline CSV + optional GeoJSON FIRST (only when present), so a host-materialized
    // input delivered via fetchInputs below can OVERRIDE /data/input.csv (a remote
    // source arrives as a fetched CSV with an empty inline csvContent).
    if (request.csvContent) {
      pyodide.FS.writeFile(WORK_DIR + "/input.csv", request.csvContent);
      duckRegister(WORK_DIR + "/input.csv", textBytes(request.csvContent));
    }
    if (request.geojsonContent) pyodide.FS.writeFile(WORK_DIR + "/input.geojson", request.geojsonContent);

    // Host-materialized inputs (D11/D13 / option B): FETCH each same-origin token URL
    // (connect-src 'self') and write the raw bytes to its FS path — LAST, so they win
    // over the inline CSV. The remote fetch already happened host-side through the Rust
    // egress core — the worker only ever touches a local, run-scoped same-origin URL.
    for (const inp of (request.fetchInputs || [])) {
      const resp = await fetch(inp.url);
      if (!resp.ok) throw new Error("input fetch failed (" + resp.status + "): " + inp.path);
      const bytes = new Uint8Array(await resp.arrayBuffer());
      const slash = inp.path.lastIndexOf("/");
      if (slash > 0) pyodide.FS.mkdirTree(inp.path.slice(0, slash));
      pyodide.FS.writeFile(inp.path, bytes);
      duckRegister(inp.path, bytes);
    }

    const duckShim = request.duckdb ? ${JSON.stringify(DUCKDB_PY_SHIM)} + "\\n" : "";
    const composed = ${JSON.stringify(WASM_PRELUDE)} + "\\n" + duckShim + request.code;

    // Pre-flight undefined-name lint (parity with the Docker container's
    // lintScript): the SAME shared checker runs over the SAME composed script,
    // and a finding fails fast with the SAME retry-facing message — before a
    // NameError can fire on the last line of a multi-minute scan. Best-effort:
    // a lint hiccup never blocks a legitimate analysis.
    try {
      pyodide.FS.writeFile(WORK_DIR + "/script.py", composed);
      const markers = String(pyodide.runPython(${JSON.stringify(LINT_WRAPPER)}) || "");
      const undef = []; let syntax = null;
      for (const line of markers.split("\\n")) {
        const t = line.trim();
        if (t.startsWith("UNDEFINED:")) {
          const r = t.slice(10); const i = r.lastIndexOf(":");
          undef.push(i >= 0 ? r.slice(0, i) : r);
        } else if (t.startsWith("SYNTAX:")) {
          const r = t.slice(7); const i = r.lastIndexOf(":");
          syntax = i >= 0 ? r.slice(0, i) : r;
        }
      }
      if (syntax || undef.length) {
        const detail = syntax !== null
          ? syntax
          : Array.from(new Set(undef)).map((n) => "\\u0060" + n + "\\u0060").join(", ");
        const template = syntax !== null
          ? ${JSON.stringify(LINT_SYNTAX_TEMPLATE)}
          : ${JSON.stringify(LINT_UNDEF_TEMPLATE)};
        self.postMessage({
          id, exitCode: 1, output: null,
          // Function replacer: a syntax-error message containing $& / $' must
          // not be interpreted as replacement patterns.
          stderr: template.replace("__HERMETIC_LINT_DETAIL__", () => detail),
        });
        return;
      }
    } catch (_lintErr) { /* best-effort — proceed to the real run */ }

    // Same prelude + exit semantics as the Node executor: a Python exception →
    // exitCode 1 + stderr.txt, so the sidecar's parseSandboxOutput error path
    // lights up identically to Docker.
    let exitCode = 0;
    try {
      await pyodide.runPythonAsync(composed);
    } catch (err) {
      exitCode = 1;
      pyodide.FS.writeFile(WORK_DIR + "/stderr.txt", String((err && err.message) || err));
    }
    const read = (p) => { try { return pyodide.FS.readFile(p, { encoding: "utf8" }); } catch { return null; } };
    self.postMessage({
      id,
      exitCode,
      output: read(WORK_DIR + "/output.json"),
      stderr: read(WORK_DIR + "/stderr.txt") || undefined,
    });
  } catch (err) {
    // Boot/stage failure — report a non-zero envelope so the sidecar resolves.
    self.postMessage({ id, exitCode: 1, output: null, stderr: String((err && err.message) || err) });
  }
};
`;
