import { describe, it, expect } from "vitest";
import { catalog } from "@/lib/catalog";

// Modularization M0-0c: catalog.prompt() authors the system prompt behind
// every composed spec in the product, and today its text is generated by the
// pinned @json-render 0.x dependency. This snapshot makes any change to that
// text — a dependency bump, a catalog edit, or the WS2 in-house fork — show
// up as a reviewable diff instead of a silent output-quality shift.
// The WS2 fork must reproduce this snapshot byte-identically before the
// upstream dependency is removed.

describe("catalog.prompt() stability", () => {
  it("matches the committed snapshot", async () => {
    const prompt = (catalog as unknown as { prompt: (opts?: object) => string }).prompt();
    await expect(prompt).toMatchFileSnapshot("__snapshots__/catalog-prompt.snap.txt");
  });
});
